force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>주문서</label>
    <nameField>
        <displayFormat>IT-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>주문서</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>판매 지점</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>주문서</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>고객명</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>주문서</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Final_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Amount__c</fullName>
    <label>결제 금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/List_Product__c.field-meta.xml
<CustomField>
    <fullName>List_Product__c</fullName>
    <label>제품 리스트</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order_Refund__c/Order_Refund__c.object-meta.xml
<CustomObject>
    <description>환불된 주문건</description>
    <label>환불</label>
    <nameField>
        <displayFormat>Refund-{0000}</displayFormat>
        <label>환불 번호</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>환불</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Refund__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>판매 지점</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>환불</relationshipLabel>
    <relationshipName>Order_Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Refund__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>환불 금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Refund__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>고객명</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>환불</relationshipLabel>
    <relationshipName>Refunds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Refund__c/fields/Order_Name__c.field-meta.xml
<CustomField>
    <fullName>Order_Name__c</fullName>
    <label>주문서</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Refund__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>환불 사유</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Refund__c/fields/Refund_Date__c.field-meta.xml
<CustomField>
    <fullName>Refund_Date__c</fullName>
    <label>환불 날짜</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Refund__c/fields/Refund_Product_List__c.field-meta.xml
<CustomField>
    <fullName>Refund_Product_List__c</fullName>
    <label>환불된 제품 리스트</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RefundController.cls
public with sharing class RefundController {
    @AuraEnabled
    public static Id createRefund(Id orderId, String refundReason) {
        try {
        // 주문 정보 조회
        Order__c orderToRefund = [SELECT Id, Name, Final_Amount__c, Account_Name__c, Contact_Name__c, Contact_Name__r.Id, List_Product__c FROM Order__c WHERE Id = :orderId LIMIT 1];
        
        // 환불 레코드 생성 및 필요한 정보 할당
        Order_Refund__c newRefund = new Order_Refund__c(
            Amount__c = orderToRefund.Final_Amount__c, 
            Refund_Date__c = Date.today(),
            Reason__c = refundReason,
            Account_Name__c = orderToRefund.Account_Name__c,
            Order_Name__c = orderToRefund.Name,
            Refund_Product_List__c = orderToRefund.List_Product__c,
            Contact_Name__c = orderToRefund.Contact_Name__c 
        );
        
        insert newRefund;
        // 환불 레코드 생성되면 해당 주문 삭제
        delete orderToRefund;
        return orderToRefund.Contact_Name__r.Id;
        } catch(Exception e){
            throw new AuraHandledException('Error: ' + e.getMessage()); // 오류 발생 시 예외 던지기
        }
    }
}