force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>주문서</label>
    <nameField>
        <displayFormat>IT-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>주문서</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>고객명</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>주문서</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <label>할인율</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>주문 날짜</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/Ordered_Product__c.object-meta.xml
<CustomObject>
    <label>주문 상품</label>
    <nameField>
        <label>Orderd Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>주문 상품</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordered_Product__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>주문서</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>주문 상품</relationshipLabel>
    <relationshipName>Ordered_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpdateCustomerPurchaseBatch.cls
global with sharing class UpdateCustomerPurchaseBatch implements Database.Batchable<SObject>{
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        Date startDate = Date.today().addDays(-90);
        Date endDate = Date.today();
        return Database.getQueryLocator([
            SELECT Id, Contact_Name__c, Start_Date__c, (SELECT id, Name, Price__c, Quantity__c  FROM Ordered_Products__r), Discount_Percent__c
            FROM Order__c
            WHERE Start_Date__c >= :startDate AND Start_Date__c <= :endDate
        ]);
    }

    global void execute(Database.BatchableContext bc, List<Order__c> scope){

        CustomerPurchaseManager.UpdatePurchaseAmountForCustomer(scope);
        StorePurchaseManager.UpdateStorePurchaseAmountForCustomer(scope);

    }

    global void finish(Database.BatchableContext bc){

        System.debug('Batch job completed successfully.');

    }

    // Database.executeBatch(new CustomerPurchaseBatch());
}