force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>주문서</label>
    <nameField>
        <displayFormat>IT-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>주문서</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>고객명</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>주문서</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>주문 날짜</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/Ordered_Product__c.object-meta.xml
<CustomObject>
    <label>주문 상품</label>
    <nameField>
        <label>Orderd Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>주문 상품</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordered_Product__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>주문서</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>주문 상품</relationshipLabel>
    <relationshipName>Ordered_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpdatePurchaseAmountSchedule.cls
global class UpdatePurchaseAmountSchedule implements Schedulable {
    global void execute(SchedulableContext ctx) {
        // 매일 실행되는 작업 수행
        List<Order__c> orders = [SELECT Id, Contact_Name__c, Start_Date__c, (select id from Ordered_Products__r)
                               FROM Order__c
                              WHERE Start_Date__c >= LAST_N_DAYS:90];
        
        CustomerPurchaseManager.updatePurchaseAmountForCustomer(orders);
    }

    /*UpdatePurchaseAmountSchedule schedule = new UpdatePurchaseAmountSchedule();
    String jobId = System.schedule('Update Purchase Amount', '0 0 0 * * ?', schedule);*/
}