force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>주문서</label>
    <nameField>
        <displayFormat>IT-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>주문서</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>판매 지점</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>주문서</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>고객명</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>주문서</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>주문 날짜</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>총 금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/Ordered_Product__c.object-meta.xml
<CustomObject>
    <label>주문 상품</label>
    <nameField>
        <label>Orderd Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>주문 상품</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ordered_Product__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>주문서</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>주문 상품</relationshipLabel>
    <relationshipName>Ordered_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ordered_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>제품명</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>주문 상품</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactController.cls
public with sharing class ContactController {

    //전화번호로 고객 리스트 검색하는 메서드 @하원
    @AuraEnabled(cacheable=true)
    public static List<Contact> findContactByPhone(String phone) {

        String searchPhone = '%' + phone + '%';
        
        List<Contact> contacts = [SELECT Id,name,phone,Tier__c,Total_Sum__c ,Case_Count__c
                            FROM Contact 
                            WHERE Phone LIKE :searchPhone];
                            System.debug('contacts : '+ contacts);
        return (contacts != null) ? contacts : null;

    }


    //고객 id를 사용해서 해당 고객의 주문된 제품 목록을 검색하는 메서드 @하원
    @AuraEnabled(cacheable=true)
    public static List<Ordered_Product__c> getOrderedProductsByContactId(Id contactId) {

        return [SELECT  Id, 
                    Product__c,  
                    Product__r.Name,  
                    Product__r.Price__c,  
                    Quantity__c, //수량
                    Order__r.Total_Amount__c ,
                    Order__r.start_Date__c, //주문일자
                    Order__r.Account_Name__c //판매지점 id
                    
                FROM Ordered_Product__c
                WHERE Order__r.Contact_Name__c = :contactId];
    
}
}